### ISSUE TITLE
Indentation breaks after line starting with tick - for example - `uvm_info

### ISSUE THREAD

**Issue by ninadpachpute** [nachumk/systemverilog.vim#6]
If we visual-select following snippet and hit '=' then the code after tick is not auto-indented correctly.

Snapshot:

![image](https://cloud.githubusercontent.com/assets/147304/5851143/a495e08e-a228-11e4-978a-30256580c797.png)

Snippet:

```
class test;

  function void my_function(bit x);
    addr_array = new[port+1];
    size_array = new[port];

    foreach(addr_array[i])
      addr_array[i] = i==(addr_array.size-1) ? end_addr : ((end_addr - start_addr)/port+1) * i;

    addr_array.sort;

    foreach(addr_array[i])
      `uvm_info(tID, $sformatf("addr = %h", addr_array[i]), UVM_MEDIUM)

      foreach(size_array[i]) begin
        size_array[i] = (fix_len == 1) ? size : $urandom_range(256, 1);
      end
    endfunction

  endclass : test
```

**Comment by nachumk** [comment]
What can be hidden in a macro is virtually anything. The script looks for a semicolon to delimit statements and since statements can span multiple lines this is necessary. The best I can suggest is to add a semicolon after the macro. Perhaps I'll find time in the future to implement something better. Suggestions welcome.
